### ISSUE TITLE
local-udp check has failed. No check file found

### ISSUE THREAD

**Issue by jpartain89** [lux4rd0/weatherflow-dashboards-aio#6]
I've found myself in a situation where it seems the data on some of my boards has stopped populating for some reason, and for the life of me I can't quite figure this one out!

Its specifically related to the ``local-udp``, and getting the "Device Details" info to populate.

My log files keep showing this same block all the time:

```
wxfdashboardsaio_influxdb            | [httpd] 192.168.48.3 - weatherflow [07/Sep/2022:01:15:11 -0500] "POST /write?db=weatherflow HTTP/1.1 " 204 0 "-" "curl/7.64.0" 6de255dc-2e74-11ed-aa1f-0242c0a83004 3092
wxfdashboardsaio-collector-08ce4425  | health-check: Wed Sep  7 01:15:11 CDT 2022 - remote-socket check is less than 65 seconds old
wxfdashboardsaio_influxdb            | [httpd] 192.168.48.3 - weatherflow [07/Sep/2022:01:15:11 -0500] "POST /write?db=weatherflow HTTP/1.1 " 204 0 "-" "curl/7.64.0" 6de3d328-2e74-11ed-aa20-0242c0a83004 2919
wxfdashboardsaio-collector-08ce4425  | health-check: Wed Sep  7 01:15:11 CDT 2022 - remote-rest check is less than 65 seconds old
wxfdashboardsaio_influxdb            | [httpd] 192.168.48.3 - weatherflow [07/Sep/2022:01:15:11 -0500] "POST /write?db=weatherflow HTTP/1.1 " 204 0 "-" "curl/7.64.0" 6de52f82-2e74-11ed-aa21-0242c0a83004 2801
wxfdashboardsaio-collector-08ce4425  | health-check: Wed Sep  7 01:15:11 CDT 2022 - remote-forecast check is less than 305 seconds old
wxfdashboardsaio_influxdb            | [httpd] 192.168.48.3 - weatherflow [07/Sep/2022:01:15:11 -0500] "POST /write?db=weatherflow HTTP/1.1 " 204 0 "-" "curl/7.64.0" 6de66274-2e74-11ed-aa22-0242c0a83004 2845
wxfdashboardsaio-collector-08ce4425  | health-check: Wed Sep  7 01:15:11 CDT 2022 - local-udp check has failed. No check file found.
wxfdashboardsaio-collector-08ce4425  | Terminated
wxfdashboardsaio-collector-08ce4425  |
wxfdashboardsaio-collector-08ce4425  | health-check: Wed Sep  7 01:15:11 CDT 2022 - local-udp restarted.
wxfdashboardsaio-collector-08ce4425  | local-udp: Wed Sep  7 01:15:11 CDT 2022 - Starting WeatherFlow Collector (start-local-udp.sh) - https://github.com/lux4rd0/weatherflow-collector
```

And this is, kinda obviously, comes out of grafana.

![Screen Shot 2022-09-07 at 01 18 18 AM](https://user-images.githubusercontent.com/10989696/188803981-fcaf5d97-ccff-44a6-9cd3-9a044ce16d46.png)

I've also seemed to have lost my Historical collection, now, too...

![Screen Shot 2022-09-07 at 01 27 46 AM](https://user-images.githubusercontent.com/10989696/188804884-ac66166f-b54c-4c9e-b78a-3f7b8d6a6912.png)

And "Historical - Remote" is fine, along with "System Stats".

![Screen Shot 2022-09-07 at 01 33 14 AM](https://user-images.githubusercontent.com/10989696/188805928-ade452c3-5db5-4046-a2d6-57a269877374.png)
![Screen Shot 2022-09-07 at 01 33 32 AM](https://user-images.githubusercontent.com/10989696/188806024-26f3ce58-ea58-480a-b17a-2e4549ad88c6.png)

"Today So Far - Local UDP" is not working, of course. But "Today So Far - Remote" is just fine, other than the lack of lightning-strike data. 

![Screen Shot 2022-09-07 at 01 33 45 AM](https://user-images.githubusercontent.com/10989696/188806113-ebc9ffd5-5506-4a63-a368-b07f7393d20d.png)

![Screen Shot 2022-09-07 at 01 34 01 AM](https://user-images.githubusercontent.com/10989696/188806365-5f26019b-cd11-47b3-8eff-a2690a6dc57e.png)

And the docker-compose.yml file:

```yaml
version: '3.3'
services:

  wxfdashboardsaio_influxdb:
    container_name: wxfdashboardsaio_influxdb
    env_file:
      - ./.env
    image: influxdb:1.8
    restart: always
    volumes:
      - /docker/weatherflow/influxdb:/var/lib/influxdb:rw
    ports:
      - 8086:8086
    networks:
      - grafana-external
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086"]
      interval: 30s
      timeout: 10s
      retries: 5

  wxfdashboardsaio-collector:
    container_name: wxfdashboardsaio-collector-08ce4425
    env_file:
      - ./.env
    restart: always
    depends_on:
      - "wxfdashboardsaio_influxdb"
    image: lux4rd0/weatherflow-collector:latest
    ports:
      - 50222:50222/udp
    networks:
      - grafana-external
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50222"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  grafana-external:
    external: true
    name: grafana-external
```

And my sanitized .env file

```
TZ=America/Chicago
INFLUXDB_ADMIN_PASSWORD=op://dev/WeatherFlowDashboards/INFLUXDB/INFLUXDB_ADMIN_PASSWORD
INFLUXDB_ADMIN_USER=op://dev/WeatherFlowDashboards/INFLUXDB/INFLUXDB_ADMIN_USER
INFLUXDB_DATA_ENGINE=tsm1
INFLUXDB_DB=weatherflow
INFLUXDB_HTTP_LOG_ENABLED="true"
INFLUXDB_LOGGING_FORMAT=json
INFLUXDB_LOGGING_LEVEL=info
INFLUXDB_MONITOR_STORE_DATABASE=_internal
INFLUXDB_MONITOR_STORE_ENABLED="true"
INFLUXDB_REPORTING_DISABLED="false"
INFLUXDB_USER=op://dev/WeatherFlowDashboards/INFLUXDB/INFLUXDB_USER
INFLUXDB_USER_PASSWORD=op://dev/WeatherFlowDashboards/INFLUXDB/INFLUXDB_USER_PASSWORD
WEATHERFLOW_COLLECTOR_DEBUG="true"
WEATHERFLOW_COLLECTOR_DEBUG_CURL="false"
WEATHERFLOW_COLLECTOR_DISABLE_HEALTH_CHECK="false"
WEATHERFLOW_COLLECTOR_DISABLE_HOST_PERFORMANCE="false"
WEATHERFLOW_COLLECTOR_DISABLE_LOCAL_UDP="false"
WEATHERFLOW_COLLECTOR_DISABLE_REMOTE_FORECAST="false"
WEATHERFLOW_COLLECTOR_DISABLE_REMOTE_REST="false"
WEATHERFLOW_COLLECTOR_DISABLE_REMOTE_SOCKET="false"
WEATHERFLOW_COLLECTOR_HEALTHCHECK="true"
WEATHERFLOW_COLLECTOR_HOST_HOSTNAME=jpserver
WEATHERFLOW_COLLECTOR_COLLECTOR_TYPE='local-udp remote-forcast remote-rest remote-import remote-socket host-performance'
WEATHERFLOW_COLLECTOR_FUNCTION='collector import'
WEATHERFLOW_COLLECTOR_INFLUXDB_PASSWORD=op://dev/WeatherFlowDashboards/COLLECTOR/WEATHERFLOW_COLLECTOR_INFLUXDB_PASSWORD
WEATHERFLOW_COLLECTOR_INFLUXDB_URL=http://wxfdashboardsaio_influxdb:8086/write?db=weatherflow
WEATHERFLOW_COLLECTOR_INFLUXDB_USERNAME=op://dev/WeatherFlowDashboards/COLLECTOR/WEATHERFLOW_COLLECTOR_INFLUXDB_USERNAME
WEATHERFLOW_COLLECTOR_TOKEN=op://dev/WeatherFlowDashboards/COLLECTOR/WEATHERFLOW_COLLECTOR_TOKEN
WEATHERFLOW_COLLECTOR_DISABLE_HEALTHCHECK_LOCAL_UDP="false"
WEATHERFLOW_COLLECTOR_DISABLE_HEALTHCHECK_HOST_PERFORMANCE="false"
WEATHERFLOW_COLLECTOR_DISABLE_HEALTHCHECK_REMOTE_FORECAST="false"
WEATHERFLOW_COLLECTOR_DISABLE_HEALTHCHECK_REMOTE_REST="false"
WEATHERFLOW_COLLECTOR_DISABLE_HEALTHCHECK_REMOTE_SOCKET="false"
WEATHERFLOW_COLLECTOR_DOCKER_HEALTHCHECK_ENABLED=true
WEATHERFLOW_COLLECTOR_THREADS=10
```

I wouldn't be surprised to learn that some of these variables are overkill, unnecessary or even causing issues. It's essentially a mix of this project and your other, non-aio one cobbled together, somewhat. 

But I do love this setup, and hope I can get back to full functionality once again!

And if I missed anything or if I need to provide any other info, please let me know. 

Thank you!
